# app.py — Memory Moment v5
#
# Two-tab Gradio app:
#   Tab 1 (Caregiver Survey): collects the structured profile of the loved one.
#   Tab 2 (Find Words): runs the fine-tuned Gemma 4 model on the compressed
#                       Context block + the caregiver's situation.
#
# Survey data lives in gr.State and is shared across tabs. The Context block
# is generated by compress_v5.compress_survey — the same canonical Python
# implementation that mirrors the JS in the form spec (parity-tested).
#
# Same file runs in two environments:
#   USE_OLLAMA=true  → talks to local Ollama on Workbench (test)
#   USE_OLLAMA unset → talks to llama-server (built from llama.cpp by Dockerfile,
#                      runs as subprocess) — this is the HF Space deploy path

import os
import re
import gradio as gr

from compress_v5 import compress_survey

USE_OLLAMA = os.getenv("USE_OLLAMA", "false").lower() == "true"
MODEL_ID = "memory-moment-v5"
MODEL_FILE = "memory-moment-v5-Q4_K_M.gguf"
HF_REPO = "michi883/memory-moment-v5-gemma4-e2b-gguf"
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "memory-moment")
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434")

SYSTEM_PROMPT = (
    "You help a family caregiver find words that work in a hard moment "
    "with someone they love who has memory loss. The caregiver provides "
    "context about the loved one — their relationship, voice, things they "
    "often say, what calms them, what to avoid, what they resist — "
    "followed by a situation. "
    "Produce 3 to 5 short lines the caregiver can say out loud, each "
    "tagged with a mode: 🤝 agree-and-move, 🙂 lighten, 🫱 redirect, "
    "🛑 firm-but-kind, or 🎯 distract. Use phrases from \"often says\" when "
    "they fit naturally, or paraphrase the loved one's voice when they "
    "don't. Skip modes that don't fit. Output only the lines."
)

MODE_LABELS = {
    "🤝": "Agree & move on",
    "🙂": "Lighten it",
    "🫱": "Redirect",
    "🛑": "Firm but kind",
    "🎯": "Distract",
}
MODE_EMOJIS = set(MODE_LABELS.keys())


# ───────────────────────────────────────────────────────────────────
# Backend dispatch — Ollama (Workbench) or llama-server (Space)
# (Unchanged from v4. See app_v4.py for context.)
# ───────────────────────────────────────────────────────────────────

if USE_OLLAMA:
    import httpx

    def call_model(user_prompt: str) -> str:
        try:
            response = httpx.post(
                f"{OLLAMA_URL}/api/chat",
                json={
                    "model": OLLAMA_MODEL,
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    "stream": False,
                    "think": False,
                    "options": {
                        "temperature": 0.75,
                        "top_p": 0.92,
                        "top_k": 40,
                        "repeat_penalty": 1.1,
                        "num_predict": 220,
                    },
                },
                timeout=120,
            )
        except httpx.HTTPError as e:
            raise RuntimeError(f"Could not reach Ollama at {OLLAMA_URL}: {e}")

        if response.status_code != 200:
            raise RuntimeError(
                f"Ollama returned HTTP {response.status_code}: {response.text[:500]}"
            )

        data = response.json()
        content = data.get("message", {}).get("content", "")
        if not content.strip():
            raise RuntimeError(
                f"Ollama returned empty content. "
                f"Model: {OLLAMA_MODEL}. "
                f"Done reason: {data.get('done_reason', 'unknown')}. "
                f"Eval count: {data.get('eval_count', 0)}. "
                f"Full response: {str(data)[:600]}"
            )
        return content

else:
    import subprocess
    import time
    import httpx
    from huggingface_hub import hf_hub_download

    LLAMA_SERVER_URL = "http://127.0.0.1:8080"

    print(f"Downloading {MODEL_FILE} from Hugging Face...")
    model_path = hf_hub_download(
        repo_id=HF_REPO,
        filename=MODEL_FILE,
        cache_dir="/home/user/.cache/huggingface",
    )
    print(f"Model at: {model_path}")

    print("Starting llama-server...")
    server_proc = subprocess.Popen([
        "llama-server",
        "-m", model_path,
        "--host", "127.0.0.1",
        "--port", "8080",
        "-c", "2048",
        "-t", "2",
        "--jinja",
    ])

    for attempt in range(60):
        try:
            r = httpx.get(f"{LLAMA_SERVER_URL}/health", timeout=2)
            if r.status_code == 200:
                print(f"llama-server ready after {attempt * 2}s.")
                break
        except Exception:
            pass
        time.sleep(2)
    else:
        raise RuntimeError("llama-server failed to start within 120 seconds")

    def call_model(user_prompt: str) -> str:
        try:
            r = httpx.post(
                f"{LLAMA_SERVER_URL}/v1/chat/completions",
                json={
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    "temperature": 0.75,
                    "top_p": 0.92,
                    "top_k": 40,
                    "repeat_penalty": 1.1,
                    "max_tokens": 220,
                    "stream": False,
                    "chat_template_kwargs": {"enable_thinking": False},
                },
                timeout=120,
            )
        except httpx.HTTPError as e:
            raise RuntimeError(f"Could not reach llama-server: {e}")

        if r.status_code != 200:
            raise RuntimeError(f"llama-server returned HTTP {r.status_code}: {r.text[:500]}")

        data = r.json()
        try:
            message = data["choices"][0]["message"]
            content = message.get("content", "") or ""
        except (KeyError, IndexError):
            raise RuntimeError(f"Unexpected response shape: {str(data)[:600]}")

        if not content.strip():
            reasoning = message.get("reasoning_content", "") or ""
            if reasoning.strip():
                return reasoning

        if not content.strip():
            raise RuntimeError(f"llama-server returned empty content. Full: {str(data)[:600]}")
        return content


# ───────────────────────────────────────────────────────────────────
# Sample profiles — the three v4 personas, now in the v5 survey shape.
# ───────────────────────────────────────────────────────────────────

PROFILES = {
    "martha_01": {
        "display": "Martha — mother (warm, dry, patient)",
        "name_used": "Mom",
        "relationship": "mother",
        "phrases_she_says": [
            "He means well.", "It is what it is.", "Don't fuss.",
            "I'm fine.", "Oh — sit down.", "A little tired, is all.",
        ],
        "voice_tags": ["warm", "dry", "patient"],
        "important_people": [
            {"name": "Frank", "relation": "husband", "living": True},
            {"name": "Anna", "relation": "daughter", "living": True},
            {"name": "Walter", "relation": "father", "living": False},
        ],
        "what_calms_her": ["tea_or_coffee", "sitting_quietly"],
        "repeats_she_makes": ["Where is Frank?", "Did I take my pills?"],
        "topics_to_avoid": [{"topic_or_name": "Walter"}],
        "hard_times_of_day": ["late_afternoon"],
        "things_she_resists": [],
    },
    "frank_07": {
        "display": "Frank — father (dry, steady, blunt)",
        "name_used": "Dad",
        "relationship": "father",
        "phrases_she_says": [
            "Huh.", "Is it a thing?", "Drive careful.",
            "That's it.", "You eat?", "My fault.",
        ],
        "voice_tags": ["dry", "steady", "blunt"],
        "important_people": [
            {"name": "Maria", "relation": "wife", "living": True},
            {"name": "Tom", "relation": "son", "living": True},
        ],
        "what_calms_her": ["sitting_quietly", "the_outdoors"],
        "repeats_she_makes": ["Where's the truck?"],
        "topics_to_avoid": [],
        "hard_times_of_day": ["evening"],
        "things_she_resists": ["doctor_visits"],
    },
    "aunt_jo_03": {
        "display": "Aunt Jo — aunt (sly, warm, sharp)",
        "name_used": "Aunt Jo",
        "relationship": "aunt",
        "phrases_she_says": [
            "Kid.", "The world is loud today.", "I'm picky.",
            "Hm.", "The plants think you're fine.",
        ],
        "voice_tags": ["sly", "warm", "sharp"],
        "important_people": [
            {"name": "Lucy", "relation": "niece", "living": True},
            {"name": "Tom", "relation": "brother", "living": True},
        ],
        "what_calms_her": ["a_familiar_show", "tea_or_coffee"],
        "repeats_she_makes": ["Are the plants watered?"],
        "topics_to_avoid": [{"topic_or_name": "the apartment fire"}],
        "hard_times_of_day": ["night"],
        "things_she_resists": [],
    },
}

# Vocabularies — single source of truth for both compressor and form choices.
RELATIONSHIP_CHOICES = [
    "mother", "father", "spouse", "wife", "husband",
    "grandmother", "grandfather", "aunt", "uncle",
    "sibling", "sister", "brother", "friend", "other",
]
VOICE_TAG_CHOICES = [
    "warm", "dry", "firm", "soft", "quiet", "brisk", "gentle", "sly",
    "plain", "steady", "fond", "certain", "kind", "sharp", "blunt",
    "patient", "weary",
]
CALM_CHOICES = [
    ("tea or coffee", "tea_or_coffee"),
    ("music", "music"),
    ("photos", "photos"),
    ("a walk", "a_walk"),
    ("holding hands", "holding_hands"),
    ("sitting quietly", "sitting_quietly"),
    ("a familiar show", "a_familiar_show"),
    ("someone visiting", "a_specific_person_visiting"),
    ("prayer", "prayer"),
    ("food", "food"),
    ("outdoors", "the_outdoors"),
    ("a blanket", "a_blanket_or_cushion"),
]
HARD_TIME_CHOICES = [
    ("morning", "morning"),
    ("midday", "midday"),
    ("late afternoon", "late_afternoon"),
    ("evening", "evening"),
    ("night", "night"),
]
RESISTS_CHOICES = [
    ("medication", "medication"),
    ("bathing", "bathing"),
    ("dressing", "dressing"),
    ("eating", "eating"),
    ("doctor visits", "doctor_visits"),
    ("going outside", "going_outside"),
]


# ───────────────────────────────────────────────────────────────────
# Survey state helpers
# ───────────────────────────────────────────────────────────────────

def empty_survey() -> dict:
    """The starting state — what gr.State holds before anything is filled."""
    return {
        "name_used": "",
        "relationship": "",
        "phrases_she_says": [],
        "voice_tags": [],
        "important_people": [],
        "what_calms_her": [],
        "repeats_she_makes": [],
        "topics_to_avoid": [],
        "hard_times_of_day": [],
        "things_she_resists": [],
    }


def survey_is_ready(survey: dict) -> tuple[bool, list[str]]:
    """Same validation rules as the original form. Returns (ok, missing)."""
    missing = []
    if not survey.get("name_used"):
        missing.append("a name")
    if not survey.get("relationship"):
        missing.append("relationship")
    if len(survey.get("phrases_she_says", [])) < 3:
        missing.append("at least 3 phrases")
    if not survey.get("voice_tags"):
        missing.append("at least 1 voice word")
    if not survey.get("what_calms_her"):
        missing.append("at least 1 calmer")
    return (len(missing) == 0, missing)


def lines_to_list(text: str) -> list[str]:
    """Parse newline-separated textbox into a clean list."""
    return [s.strip() for s in (text or "").split("\n") if s.strip()]


def topics_to_avoid_from_text(text: str) -> list[dict]:
    """One topic per line → list of {topic_or_name: ...} dicts.
    The dict shape mirrors the form spec; v6 may add per-topic metadata.
    """
    return [{"topic_or_name": s} for s in lines_to_list(text)]


def update_survey(
    name_used: str,
    relationship: str,
    voice_tags: list,
    phrases_text: str,
    repeats_text: str,
    avoid_text: str,
    calms: list,
    hard_times: list,
    resists: list,
) -> tuple[dict, str, str]:
    """Called on every form change. Rebuilds survey state, recomputes
    Context block, returns (survey_state, context_text, status_text).
    """
    survey = {
        "name_used": (name_used or "").strip(),
        "relationship": relationship or "",
        "phrases_she_says": lines_to_list(phrases_text),
        "voice_tags": list(voice_tags or []),
        "important_people": [],  # collected nowhere in this UI; v6 work
        "what_calms_her": list(calms or []),
        "repeats_she_makes": lines_to_list(repeats_text),
        "topics_to_avoid": topics_to_avoid_from_text(avoid_text),
        "hard_times_of_day": list(hard_times or []),
        "things_she_resists": list(resists or []),
    }
    context = compress_survey(survey)
    ok, missing = survey_is_ready(survey)
    if ok:
        # Show char/token counts so caregivers see the cost of what they wrote.
        # ~4 chars/token is the standard rule of thumb for English BPE.
        chars = len(context)
        tokens = (chars + 3) // 4
        status = f"✓ ready · {chars} chars · ~{tokens} tokens"
    else:
        status = "still need: " + ", ".join(missing)
    return survey, context, status


def load_profile(profile_id: str):
    """When a sample profile is picked, return values for every form widget.

    Returns a tuple matching the ordered list of form widget outputs declared
    in the UI section below — order matters and must stay in sync.
    """
    if not profile_id or profile_id not in PROFILES:
        s = empty_survey()
        return ("", "", [], "", "", "", [], [], [])
    p = PROFILES[profile_id]
    phrases_text = "\n".join(p["phrases_she_says"])
    repeats_text = "\n".join(p["repeats_she_makes"])
    avoid_text = "\n".join(e["topic_or_name"] for e in p["topics_to_avoid"])
    return (
        p["name_used"],
        p["relationship"],
        list(p["voice_tags"]),
        phrases_text,
        repeats_text,
        avoid_text,
        list(p["what_calms_her"]),
        list(p["hard_times_of_day"]),
        list(p["things_she_resists"]),
    )


# ───────────────────────────────────────────────────────────────────
# Output parsing — unchanged from v4
# ───────────────────────────────────────────────────────────────────

def parse_lines(raw: str) -> str:
    """Convert raw model output into Markdown cards.

    Visual hierarchy:
      - Mode label (e.g. "AGREE & MOVE ON") renders as a small dimmed
        tag above each line — caption-weight, not competing for attention.
      - The line itself (e.g. "🤝 He means well.") renders as the big
        readable headline. That's what the caregiver is looking for.
    """
    if not raw or not raw.strip():
        return "_The model returned an empty response. See terminal for details._"

    cleaned = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
    if not cleaned:
        cleaned = raw

    cards = []
    for line in cleaned.split("\n"):
        line = line.strip()
        if not line:
            continue
        first_emoji = None
        rest = ""
        for emoji in MODE_EMOJIS:
            if line.startswith(emoji):
                first_emoji = emoji
                rest = line[len(emoji):].strip()
                break
        if first_emoji and rest:
            label = MODE_LABELS[first_emoji].upper()
            # Inline HTML for the label gives us actual control over size /
            # opacity, which Gradio's Markdown alone doesn't (italic + small
            # tag still render at body weight).
            tag = (
                f'<div style="font-size: 0.72em; letter-spacing: 0.1em; '
                f'opacity: 0.55; margin-bottom: 0.25em;">{label}</div>'
            )
            cards.append(f"{tag}\n\n## {first_emoji} {rest}")
    if cards:
        return "\n\n".join(cards)
    return (
        f"```\n{raw.strip()}\n```\n\n"
        f"*(could not parse mode tags — raw model output above)*"
    )


# ───────────────────────────────────────────────────────────────────
# Generator (Tab 2)
# ───────────────────────────────────────────────────────────────────

def generate_lines(survey: dict, situation: str):
    """Returns (markdown_output, context_preview).

    Reads the survey from session state — that's the linkage between Tab 1
    and Tab 2. If the survey isn't ready, surface the missing-fields message
    instead of calling the model.
    """
    ok, missing = survey_is_ready(survey or {})
    if not ok:
        return (
            f"_Fill out the survey first — still need: {', '.join(missing)}._",
            compress_survey(survey or {}),
        )
    if not situation or not situation.strip():
        return "_Describe what's happening._", compress_survey(survey)

    context = compress_survey(survey)
    user_prompt = f"{context}\n\nSituation: {situation.strip()}"

    print("─" * 60)
    print("PROMPT TO MODEL:")
    print(user_prompt)
    print("─" * 60)

    try:
        raw = call_model(user_prompt)
    except Exception as e:
        return f"**Model error**\n\n```\n{e}\n```", context

    print("RAW MODEL OUTPUT:")
    print(repr(raw))
    print("─" * 60)

    return parse_lines(raw), context


def context_for_generator(survey: dict) -> str:
    """Recompute Context block when Tab 2 is loaded or survey changes."""
    return compress_survey(survey or {})


# ───────────────────────────────────────────────────────────────────
# UI
# ───────────────────────────────────────────────────────────────────

PROFILE_CHOICES = [(p["display"], pid) for pid, p in PROFILES.items()]

with gr.Blocks(title="Memory Moment") as demo:
    # Session state — the survey dict shared across tabs.
    survey_state = gr.State(value=empty_survey())

    gr.Markdown(
        "# Memory Moment\n"
        "*Words for a family caregiver, in the moment.*"
    )

    with gr.Tabs() as tabs:
        # ─── Tab 1: Survey ────────────────────────────────────────
        with gr.Tab("1 · About them", id="survey"):
            gr.Markdown(
                "Tell the model about the person you're caring for. "
                "Every field shapes the Context block on the right — that's "
                "what the model reads, along with whatever situation you "
                "describe later."
            )

            with gr.Row():
                # Left: the form
                with gr.Column(scale=3):
                    profile_picker = gr.Dropdown(
                        choices=[("— start fresh —", "")] + PROFILE_CHOICES,
                        value="",
                        label="Load a sample profile",
                        interactive=True,
                    )

                    with gr.Row():
                        name_used = gr.Textbox(
                            label="What do you call them?",
                            placeholder="e.g., Mom, Dad, Aunt Jo",
                            scale=1,
                        )
                        relationship = gr.Dropdown(
                            choices=[("— pick one —", "")] + RELATIONSHIP_CHOICES,
                            label="Your relationship",
                            value="",
                            scale=1,
                        )

                    voice_tags = gr.CheckboxGroup(
                        choices=VOICE_TAG_CHOICES,
                        label="Their voice (pick up to 3 words)",
                        info="The model uses these to tune the lines' register.",
                    )

                    phrases_text = gr.Textbox(
                        label="Phrases they often say",
                        placeholder=(
                            "One per line. Mix short and long.\n"
                            "e.g.,\n"
                            "I'm fine.\n"
                            "Don't fuss.\n"
                            "He means well."
                        ),
                        lines=5,
                        info="At least 3. The model picks up to 3 for the Context block, balanced by length.",
                    )

                    calms = gr.CheckboxGroup(
                        choices=CALM_CHOICES,
                        label="What calms them",
                        info="The first one selected appears in the Context block.",
                    )

                    hard_times = gr.CheckboxGroup(
                        choices=HARD_TIME_CHOICES,
                        label="Hard times of day",
                        info="The first one selected appears in the Context block.",
                    )

                    repeats_text = gr.Textbox(
                        label="Things they repeat (questions, refrains)",
                        placeholder=(
                            "One per line.\n"
                            "e.g.,\n"
                            "Where is Frank?\n"
                            "Did I take my pills?"
                        ),
                        lines=3,
                        info="Optional. First two appear in the Context block.",
                    )

                    avoid_text = gr.Textbox(
                        label="Topics or names to avoid",
                        placeholder=(
                            "One per line.\n"
                            "e.g.,\n"
                            "Walter\n"
                            "the apartment fire"
                        ),
                        lines=2,
                        info="Optional. The model will steer away from these.",
                    )

                    resists = gr.CheckboxGroup(
                        choices=RESISTS_CHOICES,
                        label="What they resist",
                        info="New in v5. Helps the model produce mode-appropriate firm-but-kind lines.",
                    )

                # Right: live Context preview
                with gr.Column(scale=2):
                    gr.Markdown("### What the model will see")
                    gr.Markdown(
                        "*This Context block is generated by a deterministic "
                        "function from the survey, not the model. Updates as "
                        "you type.*"
                    )
                    context_preview = gr.Code(
                        value="",
                        language=None,
                        label=None,
                        interactive=False,
                    )
                    survey_status = gr.Markdown("_Fill the form to preview._")

                    gr.Markdown(
                        "---\n"
                        "When the survey is ready, switch to **Find Words** "
                        "to describe a moment and get suggestions."
                    )

        # ─── Tab 2: Generator ─────────────────────────────────────
        with gr.Tab("2 · Find words", id="generate"):
            gr.Markdown(
                "Describe what's happening. The model produces 3–5 short lines "
                "you could say out loud."
            )

            with gr.Row():
                with gr.Column(scale=3):
                    situation = gr.Textbox(
                        label="What's happening right now?",
                        placeholder="e.g., She's annoyed her husband forgot to call.",
                        lines=3,
                    )
                    with gr.Row():
                        submit_btn = gr.Button("Generate", variant="primary")
                        regen_btn = gr.Button("Generate again")
                    output = gr.Markdown(
                        label="Lines you could say",
                        sanitize_html=False,
                    )

                with gr.Column(scale=2):
                    gr.Markdown("### What the model sees")
                    gen_context_preview = gr.Code(
                        value="",
                        language=None,
                        label=None,
                        interactive=False,
                    )
                    gr.Markdown(
                        "*If this is empty, head back to **About them** "
                        "and fill out the survey first.*"
                    )

            gr.Examples(
                examples=[
                    ["She is annoyed her husband forgot to call."],
                    ["She keeps asking where Frank is. He's at the store."],
                    ["He insists he can fix the dishwasher himself, but he can't anymore."],
                    ["He thanks his son for coming by."],
                    ["She is anxious at night and can't settle."],
                    ["She is asking the same question for the fourth time."],
                ],
                inputs=[situation],
                label="Try a situation",
            )

    gr.Markdown(
        "---\n"
        f"Model: [{MODEL_ID}-gemma4-e2b](https://huggingface.co/michi883/{MODEL_ID}-gemma4-e2b-gguf) "
        "(fine-tuned Gemma 4 E2B). Built for the Gemma 4 Good Hackathon."
    )

    # ─── Wiring ───────────────────────────────────────────────────
    # Every form input change → rebuild survey state, refresh preview.
    # The list of inputs here must match the update_survey signature.
    form_inputs = [
        name_used, relationship, voice_tags, phrases_text,
        repeats_text, avoid_text, calms, hard_times, resists,
    ]
    form_outputs = [survey_state, context_preview, survey_status]

    for component in form_inputs:
        component.change(
            fn=update_survey,
            inputs=form_inputs,
            outputs=form_outputs,
        )

    # Sample profile → fill all form fields, then re-run update_survey
    # so state and preview catch up.
    profile_picker.change(
        fn=load_profile,
        inputs=profile_picker,
        outputs=[
            name_used, relationship, voice_tags, phrases_text,
            repeats_text, avoid_text, calms, hard_times, resists,
        ],
    ).then(
        fn=update_survey,
        inputs=form_inputs,
        outputs=form_outputs,
    )

    # When the user lands on Tab 2, refresh the context preview from state.
    # Gradio's tab.select fires when the tab gains focus.
    tabs.select(
        fn=context_for_generator,
        inputs=survey_state,
        outputs=gen_context_preview,
    )

    submit_btn.click(
        fn=generate_lines,
        inputs=[survey_state, situation],
        outputs=[output, gen_context_preview],
    )
    regen_btn.click(
        fn=generate_lines,
        inputs=[survey_state, situation],
        outputs=[output, gen_context_preview],
    )


if __name__ == "__main__":
    demo.launch(
        server_name="0.0.0.0",
        server_port=7860,
        theme=gr.themes.Soft(),
    )